# Smart Dependabot configuration for apt-cacher-go
# APT Caching Proxy Server in Go
# Automatically detected: Go, Docker, GitHub Actions

version: 2
updates:
  # Go dependencies (go.mod found at root)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "go"
      include: "scope"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies (Dockerfile found)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"

  # GitHub Actions dependencies (.github/workflows/*.yml found)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "actions"
      include: "scope"
    labels:
      - "dependencies"
      - "ci/cd"
    groups:
      ci-dependencies:
        patterns:
          - "actions/*"
          - "github/*"
        update-types:
          - "minor"
          - "patch"
      external-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/*"
          - "github/*"
        update-types:
          - "minor"
          - "patch"
