# file: .github/dependabot.yml
# version: 1.0.0
# guid: 0353402f-c088-44c7-b947-ef77009d2e58

# Smart Dependabot configuration for apt-cacher-go
# Supports: docker, github-actions, go

version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
    day: wednesday
    time: 09:00
    timezone: America/New_York
  open-pull-requests-limit: 3
  commit-message:
    prefix: docker
    include: scope
  labels:
  - dependencies
  - tech:docker
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: wednesday
    time: '10:00'
    timezone: America/New_York
  open-pull-requests-limit: 5
  commit-message:
    prefix: ci
    include: scope
  labels:
  - dependencies
  - github-actions
  - ci-cd
  groups:
    ci-dependencies:
      patterns:
      - actions/*
      - github/*
      update-types:
      - minor
      - patch
    external-actions:
      patterns:
      - '*'
      exclude-patterns:
      - actions/*
      - github/*
      update-types:
      - minor
      - patch
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
    timezone: America/New_York
  open-pull-requests-limit: 5
  commit-message:
    prefix: go
    include: scope
  labels:
  - dependencies
  - tech:go
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
