# apt-cacher-go advanced configuration

# Server configuration
listen_address: "0.0.0.0" # Listen on all IPv4 interfaces
port: 3142
admin_port: 3143 # Port for admin interface

# TLS configuration
tls_enabled: false
tls_port: 3144 # Changed to avoid conflict with admin port
tls_cert: "/etc/apt-cacher-go/cert.pem"
tls_key: "/etc/apt-cacher-go/key.pem"
log_file: "/var/log/apt-cacher-go.log"
log_level: "info"

# Cache configuration
cache_dir: "/mnt/bigdata/apt-cache-go"
cache_size: "40G"
cleanup_freq: "1h"

# Cache TTLs
cache_ttls:
  index: "1h" # Release files expire quickly
  package: "30d" # Packages can be cached longer

# Security
allowed_ips:
  - "0.0.0.0/0" # Allow all IPv4
  - "::/0" # Allow all IPv6
rate_limit: 100 # Requests per minute per IP
auth_enabled: false
admin_auth: false
admin_user: "admin"
admin_password: "password"

# Metrics
metrics_enabled: true

# Download queue
max_concurrent_downloads: 10

# Repository backends
backends:
  - name: "ubuntu-archive"
    url: "http://archive.ubuntu.com/ubuntu"
    priority: 100
  - name: "ubuntu-security"
    url: "http://security.ubuntu.com/ubuntu"
    priority: 90
  - name: "debian"
    url: "http://deb.debian.org/debian"
    priority: 80
  - name: "debian-security"
    url: "http://security.debian.org/debian-security"
    priority: 70

# Advanced mapping rules (optional)
mapping_rules:
  - type: "regex"
    pattern: "^(debian|ubuntu)/dists/(.*)$"
    repository: "%s"
    priority: 100
  - type: "regex"
    pattern: "^security\\.debian\\.org/(.*)$"
    repository: "security.debian.org"
    priority: 90
