# apt-cacher-go advanced configuration

# Server configuration
listen_address: "0.0.0.0" # Listen on all IPv4 interfaces
port: 3142
admin_port: 3143 # Port for admin interface

# Add this new section for HTTPS handling
https_remap:
  enabled: true # Enable transparent HTTPS-to-HTTP remapping
  verify_packages: true # Still verify package signatures

# TLS configuration
tls_enabled: false
tls_port: 3144 # Changed to avoid conflict with admin port
tls_cert: "/etc/apt-cacher-go/cert.pem"
tls_key: "/etc/apt-cacher-go/key.pem"
log_file: "/var/log/apt-cacher-go.log"
log_level: "info"

# Cache configuration
cache_dir: "/mnt/bigdata/apt-cache-go"
cache_size: "40G"
cleanup_freq: "1h"

# Cache TTLs
cache_ttls:
  index: "1h" # Release files expire quickly
  package: "30d" # Packages can be cached longer

# Security
allowed_ips:
  - "0.0.0.0/0" # Allow all IPv4
  - "::/0" # Allow all IPv6
rate_limit: 100 # Requests per minute per IP
auth_enabled: false
admin_auth: false
admin_user: "admin"
admin_password: "password"

# Metrics
metrics_enabled: true

# Download queue
max_concurrent_downloads: 10

# Prefetching configuration
prefetch_enabled: true
max_prefetches: 10
# Add architecture filtering to reduce 404 errors
architectures:
  - amd64 # x86_64 architecture (most common)
  # - i386 # 32-bit x86 architecture
  # Comment out architectures you don't need
  # - armhf   # ARM hard float (Raspberry Pi, etc.)
  - arm64 # 64-bit ARM
  # - ppc64el # PowerPC 64-bit little endian
  # - s390x   # IBM System z
  # - riscv64 # RISC-V 64-bit

# Key management (new section)
key_management:
  enabled: true
  auto_retrieve: true
  key_ttl: "365d"
  keyservers:
    - "hkp://keyserver.ubuntu.com:80"
    - "hkp://keys.gnupg.net:80"
    - "hkp://pool.sks-keyservers.net:80"
  key_dir: "/var/lib/apt-cacher-go/keys"

# Repository configuration
disable_default_repos: false # Set to true to disable built-in repository definitions

# Repository backends
backends:
  # Third-party repositories with explicit HTTP URLs
  - name: "docker"
    url: "http://download.docker.com/linux/ubuntu"
    priority: 60
  - name: "grafana"
    url: "http://packages.grafana.com/oss/deb"
    priority: 55
  - name: "plex"
    url: "http://downloads.plex.tv/repo/deb"
    priority: 50
  - name: "postgresql"
    url: "http://apt.postgresql.org/pub/repos/apt"
    priority: 45
  - name: "hwraid"
    url: "http://hwraid.le-vert.net/ubuntu"
    priority: 40

# Advanced mapping rules (optional)
mapping_rules:
  # Docker rules
  - type: "prefix"
    pattern: "docker/linux/ubuntu"
    repository: "docker"
    priority: 60

  # Grafana rules
  - type: "prefix"
    pattern: "grafana/oss/deb"
    repository: "grafana"
    priority: 55

  # Plex rules
  - type: "prefix"
    pattern: "plex/repo/deb"
    repository: "plex"
    priority: 50

  # PostgreSQL rules
  - type: "prefix"
    pattern: "postgresql/pub/repos/apt"
    repository: "postgresql"
    priority: 45

  # HWRaid rules
  - type: "prefix"
    pattern: "hwraid/ubuntu"
    repository: "hwraid"
    priority: 40
