# apt-cacher-go configuration

# Server configuration
listen_address: "0.0.0.0"
port: 3142
admin_port: 3143
tls_enabled: false
tls_port: 3144
tls_cert: "/etc/apt-cacher-go/cert.pem"
tls_key: "/etc/apt-cacher-go/key.pem"
log_file: "/var/log/apt-cacher-go/apt-cacher-go.log"
log_level: "info"

# Cache configuration
cache_dir: "/var/cache/apt-cacher-go"
cache_size: "60G"
cache_ttls:
  index: "1h"
  package: "30d"
cleanup_freq: "1h"

# Security settings
allowed_ips:
  - "0.0.0.0/0" # Allow all IPv4
  - "::/0" # Allow all IPv6
rate_limit: 100 # Requests per minute per IP
auth_enabled: false
admin_auth: false
username: "admin"
password: "password"

# Metrics configuration
metrics_enabled: true

# Download queue
max_concurrent_downloads: 10

# Prefetching legacy options
prefetch_enabled: true
max_prefetches: 20
architectures:
  - amd64
  - i386

# Default repositories - set to false if you want to specify only custom repositories
disable_default_repos: false

# Key management configuration
key_management:
  enabled: true
  auto_retrieve: true
  key_ttl: "365d"
  keyservers:
    - "hkp://keyserver.ubuntu.com:80"
    - "hkp://keys.gnupg.net:80"
    - "hkp://pool.sks-keyservers.net:80"
  key_dir: "/var/cache/apt-cacher-go/keys" # Use absolute path, not relative
  key_length: 4096

# Prefetch configuration
prefetch:
  enabled: true
  max_concurrent: 10 # Reduced from 20 to prevent too many concurrent requests
  skip_notfound: true # Skip files that returned 404
  retry_limit: 1 # Only retry failed downloads once
  fail_cache_ttl: "24h" # Remember failed URLs for 24 hours
  architectures:
    - amd64
  warmup_on_startup: true
  verbose_logging: false # Controls detailed logging of prefetcher operations

# Standard repository backends (will be added automatically if missing)
backends:
  # Standard repositories
  - name: "ubuntu-archive"
    url: "http://archive.ubuntu.com/ubuntu"
    priority: 100
  - name: "ubuntu-security"
    url: "http://security.ubuntu.com/ubuntu"
    priority: 95
  - name: "debian"
    url: "http://deb.debian.org/debian"
    priority: 90
  - name: "debian-security"
    url: "http://security.debian.org/debian-security"
    priority: 85
  - name: "debian-backports"
    url: "http://deb.debian.org/debian-backports"
    priority: 80
  - name: "ubuntu-ports"
    url: "http://ports.ubuntu.com/ubuntu-ports"
    priority: 75
  # Third-party repositories
  - name: "docker"
    url: "http://download.docker.com/linux/ubuntu"
    priority: 60
  - name: "grafana"
    url: "http://packages.grafana.com/oss/deb"
    priority: 55
  - name: "plex"
    url: "http://downloads.plex.tv/repo/deb"
    priority: 50
  - name: "postgresql"
    url: "http://apt.postgresql.org/pub/repos/apt"
    priority: 45
  - name: "hwraid"
    url: "http://hwraid.le-vert.net/ubuntu"
    priority: 40

# Mapping rules for repositories
mapping_rules:
  # Standard repository mappings
  - type: "prefix"
    pattern: "archive.ubuntu.com/ubuntu"
    repository: "ubuntu-archive"
    priority: 100
  - type: "prefix"
    pattern: "security.ubuntu.com/ubuntu"
    repository: "ubuntu-security"
    priority: 95
  - type: "prefix"
    pattern: "deb.debian.org/debian"
    repository: "debian"
    priority: 90
  - type: "prefix"
    pattern: "security.debian.org/debian-security"
    repository: "debian-security"
    priority: 85
  - type: "prefix"
    pattern: "deb.debian.org/debian-backports"
    repository: "debian-backports"
    priority: 80
  - type: "prefix"
    pattern: "ports.ubuntu.com/ubuntu-ports"
    repository: "ubuntu-ports"
    priority: 75
  # Third-party repository mappings
  - type: "prefix"
    pattern: "download.docker.com/linux/ubuntu"
    repository: "docker"
    priority: 60
  - type: "prefix"
    pattern: "packages.grafana.com/oss/deb"
    repository: "grafana"
    priority: 55
  - type: "prefix"
    pattern: "downloads.plex.tv/repo/deb"
    repository: "plex"
    priority: 50
  - type: "prefix"
    pattern: "apt.postgresql.org/pub/repos/apt"
    repository: "postgresql"
    priority: 45
  - type: "prefix"
    pattern: "hwraid.le-vert.net/ubuntu"
    repository: "hwraid"
    priority: 40

# Additional metadata
metadata:
  memory_management:
    high_watermark_mb: 6144
    critical_watermark_mb: 8096
    monitor_interval: "5s"
  cache:
    flush_interval: "5m"
  # Development release handling configuration
  dev_release:
    enabled: true
    codenames:
      - "oracular"
      - "noble"
      - "devel"
      - "experimental"
    skip_missing_components:
      - "-security"
      - "-updates"
      - "-backports"
    suppress_errors: true
    prefetch_settings:
      max_concurrent: 5
      skip_notfound: true
      retry_limit: 1
