# apt-cacher-go advanced configuration

# Server configuration
listen_address: "0.0.0.0" # Listen on all IPv4 interfaces
port: 3142
admin_port: 3143 # Port for admin interface

# Add this new section for HTTPS handling
https_remap:
  enabled: true # Enable transparent HTTPS-to-HTTP remapping
  verify_packages: true # Still verify package signatures

# TLS configuration
tls_enabled: false
tls_port: 3144 # Changed to avoid conflict with admin port
tls_cert: "/etc/apt-cacher-go/cert.pem"
tls_key: "/etc/apt-cacher-go/key.pem"
log_file: "/var/log/apt-cacher-go.log"
log_level: "info"

# Cache configuration
cache_dir: "/mnt/bigdata/apt-cache-go"
cache_size: "40G"
cleanup_freq: "1h"

# Cache TTLs
cache_ttls:
  index: "1h" # Release files expire quickly
  package: "30d" # Packages can be cached longer

# Security
allowed_ips:
  - "0.0.0.0/0" # Allow all IPv4
  - "::/0" # Allow all IPv6
rate_limit: 100 # Requests per minute per IP
auth_enabled: false
admin_auth: false
admin_user: "admin"
admin_password: "password"

# Metrics
metrics_enabled: true

# Download queue
max_concurrent_downloads: 10

# Repository backends
backends:
  - name: "ubuntu-archive"
    url: "http://archive.ubuntu.com/ubuntu"
    priority: 100
  - name: "ubuntu-security"
    url: "http://security.ubuntu.com/ubuntu"
    priority: 90
  - name: "debian"
    url: "http://deb.debian.org/debian"
    priority: 80
  - name: "debian-security"
    url: "http://security.debian.org/debian-security"
    priority: 70
  # Third-party repositories with explicit HTTP URLs
  - name: "docker"
    url: "http://download.docker.com/linux/ubuntu"
    priority: 60
  - name: "grafana"
    url: "http://packages.grafana.com/oss/deb"
    priority: 55
  - name: "plex"
    url: "http://downloads.plex.tv/repo/deb"
    priority: 50
  - name: "postgresql"
    url: "http://apt.postgresql.org/pub/repos/apt"
    priority: 45
  - name: "hwraid"
    url: "http://hwraid.le-vert.net/ubuntu"
    priority: 40

# Advanced mapping rules (optional)
mapping_rules:
  - type: "regex"
    pattern: "^(debian|ubuntu)/dists/(.*)$"
    repository: "%s"
    priority: 100
  - type: "regex"
    pattern: "^security\\.debian\\.org/(.*)$"
    repository: "security.debian.org"
    priority: 90

  # Docker rules
  - type: "prefix"
    pattern: "docker/linux/ubuntu"
    repository: "docker"
    priority: 60

  # Grafana rules
  - type: "prefix"
    pattern: "grafana/oss/deb"
    repository: "grafana"
    priority: 55

  # Plex rules
  - type: "prefix"
    pattern: "plex/repo/deb"
    repository: "plex"
    priority: 50

  # PostgreSQL rules
  - type: "prefix"
    pattern: "postgresql/pub/repos/apt"
    repository: "postgresql"
    priority: 45

  # HWRaid rules
  - type: "prefix"
    pattern: "hwraid/ubuntu"
    repository: "hwraid"
    priority: 40
