# apt-cacher-go configuration

# Server configuration
listen_address: "0.0.0.0"
port: 3142
admin_port: 3143
tls_enabled: false
tls_port: 3144
tls_cert: "/etc/apt-cacher-go/cert.pem"
tls_key: "/etc/apt-cacher-go/key.pem"
log_file: "/var/log/apt-cacher-go.log"
log_level: "info"

# Cache configuration
cache_dir: "/var/cache/apt-cacher-go"
cache_size: "60G"
cache_ttls:
  index: "1h"
  package: "30d"
cleanup_freq: "1h"

# Security settings
allowed_ips:
  - "0.0.0.0/0" # Allow all IPv4
  - "::/0" # Allow all IPv6
rate_limit: 100 # Requests per minute per IP
auth_enabled: false
admin_auth: false
username: "admin"
password: "password"

# Metrics configuration
metrics_enabled: true

# Download queue
max_concurrent_downloads: 10

# Prefetching legacy options
prefetch_enabled: true
max_prefetches: 20
architectures:
  - amd64
  - i386

# Default repositories
disable_default_repos: false

# Key management configuration
key_management:
  enabled: true
  auto_retrieve: true
  key_ttl: "365d"
  keyservers:
    - "hkp://keyserver.ubuntu.com:80"
    - "hkp://keys.gnupg.net:80"
    - "hkp://pool.sks-keyservers.net:80"
  key_dir: "keys"
  key_length: 4096

# New prefetch configuration structure
prefetch:
  enabled: true
  max_concurrent: 20
  architectures:
    - amd64
    - i386
  warmup_on_startup: true

# Repository backends
backends:
  - name: "docker"
    url: "http://download.docker.com/linux/ubuntu"
    priority: 60
  - name: "grafana"
    url: "http://packages.grafana.com/oss/deb"
    priority: 55
  - name: "plex"
    url: "http://downloads.plex.tv/repo/deb"
    priority: 50
  - name: "postgresql"
    url: "http://apt.postgresql.org/pub/repos/apt"
    priority: 45
  - name: "hwraid"
    url: "http://hwraid.le-vert.net/ubuntu"
    priority: 40

# Mapping rules
mapping_rules:
  - type: "prefix"
    pattern: "docker/linux/ubuntu"
    repository: "docker"
    priority: 60
  - type: "prefix"
    pattern: "grafana/oss/deb"
    repository: "grafana"
    priority: 55
  - type: "prefix"
    pattern: "plex/repo/deb"
    repository: "plex"
    priority: 50
  - type: "prefix"
    pattern: "postgresql/pub/repos/apt"
    repository: "postgresql"
    priority: 45
  - type: "prefix"
    pattern: "hwraid/ubuntu"
    repository: "hwraid"
    priority: 40

# Additional metadata
metadata:
  memory_management:
    high_watermark_mb: 6144
    critical_watermark_mb: 8096
    monitor_interval: "5s"
  cache:
    flush_interval: "5m"
  # Add development release handling configuration
  dev_release:
    enabled: true
    codenames:
      - "oracular"
      - "noble"
      - "devel"
      - "experimental"
    skip_missing_components:
      - "-security"
      - "-updates"
      - "-backports"
    suppress_errors: true
