# Test configuration for apt-cacher-go Docker integration tests

# Server configuration
listen_address: "0.0.0.0"
port: 3142

# Cache configuration
cache_dir: "/var/cache/apt-cacher-go"
max_cache_size: 5120  # 5GB for testing

# Security - allow all for testing
allowed_ips:
  - "0.0.0.0/0"

# Admin auth for testing
admin_auth: "admin:testpassword"

# Performance settings
max_concurrent_downloads: 20
prefetch_enabled: true
prefetch_limit: 10

# Repository backends
backends:
  - name: "ubuntu-archive"
    url: "http://archive.ubuntu.com/ubuntu"
    priority: 100
  - name: "ubuntu-security"
    url: "http://security.ubuntu.com/ubuntu"
    priority: 95
  - name: "debian"
    url: "http://deb.debian.org/debian"
    priority: 90
  - name: "debian-security"
    url: "http://security.debian.org/debian-security"
    priority: 85
  - name: "kali"
    url: "http://http.kali.org/kali"
    priority: 70
