# file: .github/workflows/ci.yml
# version: 1.0.0
# guid: a7b8c9d0-e1f2-3456-789a-123456789016

name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  security-events: write

jobs:
  # Reusable CI workflow
  ci:
    name: Continuous Integration
    uses: jdfalk/ghcommon/.github/workflows/reusable-ci.yml@main
    with:
      go-version: "1.21"
      node-version: "18"
      python-version: "3.11"
      enable-dependency-submission: true
      run-lint: true
      run-test: true
      run-build: true
    secrets: inherit
